"""Add available date range to Dish

Revision ID: 38831defdaae
Revises: 671602c850ed
Create Date: 2024-12-10 02:47:45.089598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38831defdaae'
down_revision = '671602c850ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dishes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('available_start_date', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('available_end_date', sa.Date(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dishes', schema=None) as batch_op:
        batch_op.drop_column('available_end_date')
        batch_op.drop_column('available_start_date')

    # ### end Alembic commands ###
