"""add column <date> to <orders> table

Revision ID: 671602c850ed
Revises: a91b0b8cf2c2
Create Date: 2024-12-09 20:29:07.537411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '671602c850ed'
down_revision = 'a91b0b8cf2c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.Date(), nullable=True))
        batch_op.alter_column('deliver_to',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=False,
               existing_server_default=sa.text("'planta a'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('deliver_to',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False,
               existing_server_default=sa.text("'planta a'"))
        batch_op.drop_column('date')

    # ### end Alembic commands ###
