"""add column <deliver_to> to <orders> table

Revision ID: a91b0b8cf2c2
Revises: ab93e36b5aa2
Create Date: 2024-12-09 02:02:35.562481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a91b0b8cf2c2'
down_revision = 'ab93e36b5aa2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deliver_to', sa.String(length=100), nullable=False, server_default='planta a'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('deliver_to')

    # ### end Alembic commands ###
